language: node_js
node_js:
  - "stable"
  - "lts/*"

env:
  # Avoids file watcher error "ENOSPC" from using chokidar with linting
  - PARSER_NO_WATCH=true

script: npm run test

cache:
  directories: node_modules
